### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by chris-rl** [axiomhq/axiom-demo#22]
Hello,
when starting your demo via `docker compose up -d` I cannot reach the web UI on port 8080. When looking at the docker containers, I see some of them restarting over and over again.
![image](https://user-images.githubusercontent.com/51326486/137711158-ca13b514-6399-41b1-9b4b-63f5438b0fc4.png)
Also, the main container for service `axiom-core` is not running for very long (see low up time).

Any idea, what's going on here?

**Comment by bahlo** [comment]
Fixed in #23

**Comment by chris-rl** [comment]
Thanks for the super-fast fix! It's working now. :+1:
